swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /v1.0

paths:
  /category/list:
    post:
      summary: Generate app category list
      description: Generates application categories
      operationId: api.get_category_list
      produces:
        - text/plain;
      responses:
        200:
          description: Return as array
          schema:
            type: object
          examples:
            "text/plain": "[cat1,cat2,cat3]"
  /repo/list:
    post:
      summary: Generate repo list
      description: Generates repos
      operationId: api.get_repos
      produces:
        - text/plain;
      responses:
        200:
          description: Return as array
          schema:
            type: object
          examples:
            "text/plain": "[cat1,cat2,cat3]"
  /app/flatpak/{pkgName}:
    post:
      summary: Search application in flatpak
      description: Search application in flatpak
      operationId: api.search_flatpaks
      produces:
        - text/plain;
      responses:
        200:
          description: Return as array
          schema:
            type: object
          examples:
            "text/plain": "[cat1,cat2,cat3]"
      parameters:
        - name: pkgName
          in: path
          description: Name of package
          required: true
          type: string
  /app/snap/{pkgName}:
    post:
      summary: Search application in snap
      description: Search application in snap
      operationId: api.search_snaps
      produces:
        - text/plain;
      responses:
        200:
          description: Return as array
          schema:
            type: object
          examples:
            "text/plain": "[cat1,cat2,cat3]"
      parameters:
        - name: pkgName
          in: path
          description: Name of package
          required: true
          type: string